/**
 * City names used to strip trailing location noise from bank descriptions.
 *
 * Why a list instead of a heuristic: descriptions arrive uppercased, so casing
 * gives no signal, and city names vary in token count ("OAKLAND" vs "SAN
 * FRANCISCO"). Popping a fixed number of trailing tokens mangles real merchant
 * names — "BLUE BOTTLE COFFEE OAKLAND CA" loses "COFFEE". Matching against
 * known city names only strips what is actually a city.
 *
 * Coverage is the ~250 largest US cities plus common suburbs. A miss is benign:
 * the city stays in the payee, which is ugly but stable, and a learned rule
 * still matches it consistently.
 */
export const US_CITIES = new Set([
  'NEW YORK','LOS ANGELES','CHICAGO','HOUSTON','PHOENIX','PHILADELPHIA',
  'SAN ANTONIO','SAN DIEGO','DALLAS','SAN JOSE','AUSTIN','JACKSONVILLE',
  'FORT WORTH','COLUMBUS','CHARLOTTE','SAN FRANCISCO','INDIANAPOLIS','SEATTLE',
  'DENVER','WASHINGTON','BOSTON','EL PASO','NASHVILLE','DETROIT','OKLAHOMA CITY',
  'PORTLAND','LAS VEGAS','MEMPHIS','LOUISVILLE','BALTIMORE','MILWAUKEE',
  'ALBUQUERQUE','TUCSON','FRESNO','SACRAMENTO','KANSAS CITY','MESA','ATLANTA',
  'OMAHA','COLORADO SPRINGS','RALEIGH','LONG BEACH','VIRGINIA BEACH','MIAMI',
  'OAKLAND','MINNEAPOLIS','TULSA','BAKERSFIELD','WICHITA','ARLINGTON','AURORA',
  'TAMPA','NEW ORLEANS','CLEVELAND','ANAHEIM','HONOLULU','HENDERSON','STOCKTON',
  'LEXINGTON','CORPUS CHRISTI','RIVERSIDE','SANTA ANA','ORLANDO','IRVINE',
  'CINCINNATI','NEWARK','SAINT PAUL','ST PAUL','PITTSBURGH','GREENSBORO',
  'ST LOUIS','SAINT LOUIS','LINCOLN','PLANO','ANCHORAGE','DURHAM','JERSEY CITY',
  'CHANDLER','CHULA VISTA','BUFFALO','NORTH LAS VEGAS','GILBERT','MADISON',
  'RENO','TOLEDO','FORT WAYNE','LUBBOCK','ST PETERSBURG','SAINT PETERSBURG',
  'LAREDO','IRVING','CHESAPEAKE','GLENDALE','WINSTON SALEM','SCOTTSDALE',
  'GARLAND','BOISE','NORFOLK','SPOKANE','FREMONT','RICHMOND','SANTA CLARITA',
  'SAN BERNARDINO','BATON ROUGE','HIALEAH','TACOMA','MODESTO','PORT ST LUCIE',
  'HUNTSVILLE','DES MOINES','MORENO VALLEY','FONTANA','FRISCO','ROCHESTER',
  'YONKERS','FAYETTEVILLE','WORCESTER','COLUMBIA','CAPE CORAL','MCKINNEY',
  'LITTLE ROCK','OXNARD','AMARILLO','AUGUSTA','SALT LAKE CITY','MONTGOMERY',
  'BIRMINGHAM','GRAND RAPIDS','GRAND PRAIRIE','OVERLAND PARK','TALLAHASSEE',
  'HUNTINGTON BEACH','SIOUX FALLS','PEORIA','KNOXVILLE','GLENDALE','VANCOUVER',
  'PROVIDENCE','AKRON','BROWNSVILLE','MOBILE','NEWPORT NEWS','TEMPE','SHREVEPORT',
  'CHATTANOOGA','FORT LAUDERDALE','AURORA','ELK GROVE','ONTARIO','SALEM',
  'CARY','SANTA ROSA','RANCHO CUCAMONGA','EUGENE','OCEANSIDE','CLARKSVILLE',
  'GARDEN GROVE','LANCASTER','SPRINGFIELD','PEMBROKE PINES','FORT COLLINS',
  'PALMDALE','SALINAS','HAYWARD','CORONA','PATERSON','MURFREESBORO','MACON',
  'LAKEWOOD','KILLEEN','SPRINGFIELD','ALEXANDRIA','KANSAS CITY','SUNNYVALE',
  'HOLLYWOOD','ROSEVILLE','CHARLESTON','ESCONDIDO','JOLIET','JACKSON',
  'BELLEVUE','SURPRISE','NAPERVILLE','PASADENA','POMONA','BRIDGEPORT',
  'DENTON','ROCKFORD','MESQUITE','SAVANNAH','SYRACUSE','MCALLEN','TORRANCE',
  'OLATHE','VISALIA','THORNTON','FULLERTON','GAINESVILLE','WACO','WEST VALLEY CITY',
  'WARREN','HAMPTON','DAYTON','COLUMBIA','ORANGE','CEDAR RAPIDS','STAMFORD',
  'VICTORVILLE','PASADENA','ELIZABETH','NEW HAVEN','MIRAMAR','KENT','STERLING HEIGHTS',
  'CARROLLTON','CORAL SPRINGS','MIDLAND','NORMAN','ATHENS','SANTA CLARA',
  'COLUMBIA','FARGO','PEARLAND','SIMI VALLEY','TOPEKA','MERIDIAN','ALLENTOWN',
  'THOUSAND OAKS','ABILENE','VALLEJO','CONCORD','ROUND ROCK','ARVADA','CLEARWATER',
  'PALM BAY','INDEPENDENCE','LAFAYETTE','ANN ARBOR','ROCHESTER','HARTFORD',
  'COLLEGE STATION','FAIRFIELD','WILMINGTON','NORTH CHARLESTON','BILLINGS',
  'WEST PALM BEACH','BERKELEY','CAMBRIDGE','CLOVIS','WEST JORDAN','RICHARDSON',
  'BROKEN ARROW','DALY CITY','LEWISVILLE','GREEN BAY','TYLER','BURBANK',
  'SAN MATEO','REDWOOD CITY','PALO ALTO','MOUNTAIN VIEW','MENLO PARK',
  'CUPERTINO','SANTA MONICA','BEAVERTON','HILLSBORO','EVERETT','RENTON',
  'FEDERAL WAY','SPOKANE VALLEY','AUBURN','MARIETTA','ALPHARETTA','ROSWELL',
  'SANDY SPRINGS','NAPA','WALNUT CREEK','SAN RAFAEL','PLEASANTON','LIVERMORE',
  'SAN LEANDRO','ALAMEDA','EMERYVILLE','FOSTER CITY','BURLINGAME','MILLBRAE',
]);
